export const buildInProgressPayload = ({
    userId,
    programKey,
    dayIndex,
    dayName,
    totalDays,
    exercises,
    completedExercises,
    currentIndex,
    currentTimeLeft,
    elapsedSeconds,
}) => ({
    clerkUserId: userId || null,
    programKey: String(programKey || '').trim(),
    dayIndex: Number.isInteger(dayIndex) ? dayIndex : null,
    dayName: dayName || null,
    totalDays: Number.isInteger(totalDays) ? totalDays : exercises.length,
    exercises,
    completedExercises,
    currentIndex,
    currentTimeLeft,
    elapsedSeconds: Number.isFinite(Number(elapsedSeconds)) ? Math.max(0, Math.round(Number(elapsedSeconds))) : 0,
    savedAt: new Date().toISOString(),
});
